routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>'web'], function($app){
    Route::get('/', 'Home@index');
    Route::get('/logout', 'Logout@index');
    Route::get('/dashboard', 'Dashboard@index');
    Route::get('/dcss/dashboard', 'dcss\dashboard@index');
    Route::post('/sendmessage', 'Sendmessage@index');

    //admin
    Route::group(['prefix'=>'admin'], function($app){
       Route::get('/', 'Admin\HomeController@index')->name('home');
       Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
       Route::post('/login', 'Auth\LoginController@login')->name('login');
       Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
       Route::get('/categories', 'Admin\CategoriesController@index')->name('categories');

       Route::get('/configs', 'Admin\ConfigsController@index')->name('configs');
       Route::get('/buttons', 'Admin\ButtonsController@index')->name('buttons');

       //Currency Admin
       Route::resource('currencies', 'Admin\CurrenciesController');
       Route::get('/currencies/{currency}/remove', 'Admin\CurrenciesController@remove')->name('currencies.remove');
       Route::resource('categories', 'Admin\CategoriesController');
       Route::get('/categories/{category}/remove', 'Admin\CategoriesController@remove')->name('categories.remove');
       Route::get('/categories/{category}/toggleShow', 'Admin\CategoriesController@toggleShow')->name('categories.toggleShow');
       Route::resource('configs', 'Admin\ConfigsController')->except(['destroy', 'create', 'store']);
       Route::resource('buttons', 'Admin\ButtonsController');
       Route::get('/buttons/{button}/remove', 'Admin\ButtonsController@remove')->name('buttons.remove');
    });
});

resources/views/dashboard.blade.php
@extends('layouts.frontend')

@section('title')
    Dashboard
@endsection

@section('add_css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="/dcss/dashboard"/>
@endsection

@section('content')
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="alert alert-success" id="sentNotification" role="alert">
                    Message Sent, please wait 5 seconds before sending another one!
                </div>
                <h1>Twitch Whisper System</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            @foreach($categories as $category)
                <div class="col-12 {{ $category->code }}">
                    <div class="header">
                        {{ $category->name }}
                    </div>
                    <div class="buttons row">
                        @foreach($buttons as $button)
                            @if($button->category->name == $category->name)
                                <x-button :button="$button" />
                            @endif
                        @endforeach
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('add_js')
{{--    <script type="text/javascript">--}}
{{--        sendCommand('collectpoints');--}}
{{--        sendCommand('collectpointssub');--}}

{{--        setTimeout(() => {--}}
{{--            sendCommand('collectpoints');--}}
{{--            sendCommand('collectpointssub');--}}
{{--        }, 1000*60*20);--}}
{{--    </script>--}}
@endsection

resources/views/dcss_dashboard.blade.php
@foreach($css as $section)
    .{{$section->category->code}} .header {
        font-weight: bold;
        font-size: 2em;
        margin-top:10px;
        margin-bottom: 5px;
        background-color: black;
        color: white;
        display: block;
        padding-left: 15px;
    }
    .{{$section->category->code}} select{
        background: {{$section->backgroundColor}};
        color: {{$section->textColor}};
    }

    .{{$section->category->code}} button{
        background: {{$section->backgroundColor}};
        color: {{$section->textColor}};
        border: {{$section->borderSize}}px solid {{$section->borderColor}};
    }

    .{{$section->category->code}} button:hover {
        background: {{$section->hoverBackgroundColor}};
        color: {{$section->hoverTextColor}};
        border: {{$section->hoverBorderSize}}px solid {{$section->hoverBorderColor}};
    }
@endforeach

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-3">
                            <a href="{{ route('configs.index') }}" class="btn btn-primary btn-block">Configs</a>
                        </div>
                        <div class="col-3">
                            <a href="{{ route('buttons.index') }}" class="btn btn-primary btn-block">Buttons</a>
                        </div>
                        <div class="col-3">
                            <a href="{{ route('categories.index') }}" class="btn btn-primary btn-block">Categories</a>
                        </div>
                        <div class="col-3">
                            <a href="{{ route('currencies.index') }}" class="btn btn-primary btn-block">Currencies</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
@extends('layouts.frontend')

@section('title')
    Home
@endsection

@section('content')
<div class="container">
    <div class="row vh-100">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <a href="{{ $authorizationUrl }}" class="btn twitch-btn btn-lg">Authenticate Twitch Account <img src="/assets/images/twitch_logo.png" /> </a>
        </div>
    </div>
</div>
@endsection