routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>'web'], function($app){
    Route::get('/', 'Home@index');
    Route::get('/logout', 'Logout@index');
    Route::get('/dashboard', 'Dashboard@index');
    Route::get('/dcss/dashboard', 'dcss\dashboard@index');
    Route::post('/sendmessage', 'Sendmessage@index');

    //admin
    Route::group(['prefix'=>'admin'], function($app){
       Route::get('/', 'Admin\HomeController@index')->name('home');
       Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
       Route::post('/login', 'Auth\LoginController@login')->name('login');
       Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
       Route::get('/categories', 'Admin\CategoriesController@index')->name('categories');

       Route::get('/configs', 'Admin\ConfigsController@index')->name('configs');
       Route::get('/buttons', 'Admin\ButtonsController@index')->name('buttons');

       //Currency Admin
       Route::resource('currencies', 'Admin\CurrenciesController');
       Route::get('/currencies/{currency}/remove', 'Admin\CurrenciesController@remove')->name('currencies.remove');
       Route::resource('categories', 'Admin\CategoriesController');
       Route::get('/categories/{category}/remove', 'Admin\CategoriesController@remove')->name('categories.remove');
       Route::get('/categories/{category}/toggleShow', 'Admin\CategoriesController@toggleShow')->name('categories.toggleShow');
       Route::resource('configs', 'Admin\ConfigsController')->except(['destroy', 'create', 'store']);
       Route::resource('buttons', 'Admin\ButtonsController');
       Route::get('/buttons/{button}/remove', 'Admin\ButtonsController@remove')->name('buttons.remove');
    });
});

app/Models/Button.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Button extends Model {

    public $timestamps = false;

    public function category() {
        return $this->belongsTo('App\Models\Category');
    }
    public function currency() {
        return $this->belongsTo('App\Models\Currency');
    }
    public function options() {
        return $this->hasMany('App\Models\ButtonOptions');
    }
}

app/Http/Controllers/Admin/ButtonsController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Services\ButtonsService;
use App\Services\CategoryService;
use App\Services\CurrencyService;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ButtonsController extends Controller {

    use AuthenticatesUsers;
    private $service;

    public function __construct(ButtonsService $service) {
        $this->middleware('auth');
        $this->service = $service;
    }

    public function index(Request $request) {
        $buttons = $this->service->getList();
        return view('button.list', ['buttons'=>$buttons]);
    }

    public function create(Request $request, CategoryService $categoryService, CurrencyService $currencyService) {
        $categories = $categoryService->getList();
        $currencies = $currencyService->getList();
        $data = [
            'categories'=>$categories,
            'currencies'=>$currencies,
            'options'=>$this->service->getEmptyOptionsArray(),
            'custom_options'=> $this->service->getCustomOptions(0)
        ];
        return view('button.addForm', $data);
    }

    public function store(Request $request) {
        $this->service->addSingle($request->toArray());
        return redirect(route('buttons.index'))->with('status', $request->command.' has been added.');
    }

    public function edit(Request $request, $id, CategoryService $categoryService, CurrencyService $currencyService) {
        $categories = $categoryService->getList();
        $currencies = $currencyService->getList();
        $button = $this->service->getSingleById($id);
        $options = (array) $button->options->toArray();
        $custom_options = $this->service->getCustomOptions($id);

        $data = [
            'button'=>$button,
            'categories'=>$categories,
            'currencies'=>$currencies,
            'options'=>$options,
            'custom_options'=>$custom_options
        ];
        return view('button.editForm', $data);
    }

    public function update(Request $request, $id) {
        $this->service->updateSingle($id, $request->toArray());
        return redirect(route('buttons.index'));
    }

    public function remove(Request $request, $id) {
        $button = $this->service->getSingleById($id);
        return view('button.deleteForm', ['button'=>$button]);
    }

    public function destroy(Request $request, $id) {
        $button = $this->service->getSingleById($id);
        if($request->delete === "DELETE"){
            $this->service->deleteSingle($id);
            return redirect(route('buttons.index'))->with('status', $button->name . ' has been deleted');
        } else {
            $flash = [
                'status'=>'You didn\'t type DELETE in all caps',
                'status-class'=>'alert-danger'
            ];

            return redirect(route('buttons.remove', ['button'=>$button->id]))->with($flash);
        }
    }
}

app/View/Components/Lettercheckboxes.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Lettercheckboxes extends Component {

    public $options;

    public function __construct($options)
    {
        $this->options = $options;
    }

    public function isSelected($letter) {
        $selected = in_array($letter, $this->options);
        $return = $selected || $this->in_sub_array($letter);
        return $return;
    }

    private function in_sub_array($letter) {
        foreach($this->options as $option) {
            if($option['option'] == $letter) {
                return true;
            }
        }

        return false;
    }

    public function render()
    {
        return view('components.checkboxes.letters');
    }
}

app/View/Components/Mousecheckboxes.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Mousecheckboxes extends Component
{
    public $options;

    public function __construct($options) {
        $this->options = $options;
    }

    public function isSelected($mouse) {
        $selected = in_array($mouse, $this->options);
        $return = $selected || $this->in_sub_array($mouse);
        return $return;
    }

    private function in_sub_array($mouse) {
        foreach($this->options as $option) {
            if($option['option'] == $mouse) {
                return true;
            }
        }

        return false;
    }

    public function render() {
        return view('components.checkboxes.mouse');
    }
}

app/View/Components/Numbercheckboxes.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Numbercheckboxes extends Component
{
    public $options;

    public function __construct($options)
    {
        $this->options = $options;
    }

    public function isSelected($number) {
        $selected = in_array($number, $this->options);
        $return = $selected || $this->in_sub_array($number);
        return $return;
    }

    private function in_sub_array($number) {
        foreach($this->options as $option) {
            if($option['option'] == $number) {
                return true;
            }
        }

        return false;
    }

    public function render()
    {
        return view('components.checkboxes.numbers');
    }
}

app/View/Components/Specialcheckboxes.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Specialcheckboxes extends Component
{
    public $options;

    public function __construct($options) {
        $this->options = $options;
    }

    public function isSelected($special) {
        $selected = in_array($special, $this->options);
        $return = $selected || $this->in_sub_array($special);
        return $return;
    }

    private function in_sub_array($special) {
        foreach($this->options as $option) {
            if($option['option'] == $special) {
                return true;
            }
        }

        return false;
    }

    public function render() {
        return view('components.checkboxes.specials');
    }
}

app/View/Components/button.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class button extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.button');
    }
}

resources/views/button/addForm.blade.php
@extends('button.layout')

@section('page')
    <form method="post" action="{{ route('buttons.store') }}" class="col-12">
        @csrf
        <div class="row">
            <div class="form-group col-6">
                <label for="category">Category</label>
                <select name="category" id="category" class="form-control" >
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-6">
                <label for="currency">Currency</label>
                <select name="currency" id="currency" class="form-control" >
                    @foreach($currencies as $currency)
                        <option value="{{ $currency->id }}">{{ $currency->currency }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                <label for="command">Command</label>
                <input type="text" class="form-control" id="command" name="command" placeholder="Enter button command" />
            </div>
            <div class="form-group col-6">
                <label for="price">Price</label>
                <input type="text" class="form-control" id="price" name="price" placeholder="Enter button price" />
            </div>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea type="text" class="form-control" id="description" name="description" placeholder="Enter button description"></textarea>
        </div>
        <h6 class="font-weight-bold">Button Options</h6>
        <x-collectioncheckboxes />
        <x-lettercheckboxes :options="$options" />
        <x-numbercheckboxes :options="$options" />
        <x-directioncheckboxes :options="$options" />
        <x-specialcheckboxes :options="$options" />
        <x-mousecheckboxes :options="$options" />
        <x-customchoicescheckboxes :options="$custom_options" />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/button/deleteForm.blade.php
@extends('category.layout')

@section('page')
    <form method="post" action="{{ route('buttons.destroy', ['button'=>$button->id]) }}">
        {!! method_field('DELETE') !!}
        @csrf
        <div class="form-group">
            <label for="delete">To Delete the {{ $button->name }} Button, type DELETE (all caps) and press Submit</label>
            <input type="text" class="form-control" id="delete" name="delete" />
        </div>
        <button type="submit" class="btn btn-danger">Submit</button>
    </form>
@endsection

resources/views/button/editForm.blade.php
@extends('button.layout')

@section('page')
    <form method="post" action="{{ route('buttons.update', ['button'=>$button->id]) }}" class="col-12">
        @csrf
        {{ method_field('PUT') }}
        <div class="row">
            <div class="form-group col-6">
                <label for="category">Category</label>
                <select name="category" id="category" class="form-control" >
                    @foreach($categories as $category)
                        <option
                            value="{{ $category->id }}"
                            @if($button->category->id == $category->id)
                            selected="selected"
                            @endif
                        >{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-6">
                <label for="currency">Currency</label>
                <select name="currency" id="currency" class="form-control" >
                    @foreach($currencies as $currency)
                        <option
                            value="{{ $currency->id }}"
                            @if($button->currency->id == $currency->id)
                                selected="selected"
                            @endif
                        >{{ $currency->currency }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                <label for="command">Command</label>
                <input type="text" class="form-control" id="command" name="command" value="{{$button->command}}" placeholder="Enter button command" />
            </div>
            <div class="form-group col-6">
                <label for="price">Price</label>
                <input type="text" class="form-control" id="price" name="price" value="{{$button->price}}" placeholder="Enter button price" />
            </div>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea type="text" class="form-control" id="description" name="description" placeholder="Enter button description">
                {{ $button->description }}
            </textarea>
        </div>
        <h6 class="font-weight-bold">Button Options</h6>
        <x-lettercheckboxes :options="$options" />
        <x-numbercheckboxes :options="$options" />
        <x-directioncheckboxes :options="$options" />
        <x-specialcheckboxes :options="$options" />
        <x-mousecheckboxes :options="$options" />
        <x-customchoicescheckboxes :options="$custom_options" />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/button/layout.blade.php
@extends('layouts.admin_page')

@section('section')
    Button
@endsection

resources/views/button/list.blade.php
@extends('button.layout')

@section('page')
    <div class="text-right">
        <x-add-action path="buttons" name="Button" />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Command</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
                <th scope="col">Currency</th>
                <th scope="col">Category</th>
            </tr>
        </thead>
        <tbody>
            @foreach($buttons as $button)
            <tr>
                <td>{{ $button->id }}</td>
                <td>{{ $button->command }}</td>
                <td>{{ $button->description }}</td>
                <td>{{ $button->price }}</td>
                <td>{{ $button->currency->currency }}</td>
                <td>{{ $button->category->name }}</td>
                <td><x-row-actions :item="$button" path="buttons" attrib="button" /></td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection