routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>'web'], function($app){
    Route::get('/', 'Home@index');
    Route::get('/logout', 'Logout@index');
    Route::get('/dashboard', 'Dashboard@index');
    Route::get('/dcss/dashboard', 'dcss\dashboard@index');
    Route::post('/sendmessage', 'Sendmessage@index');

    //admin
    Route::group(['prefix'=>'admin'], function($app){
       Route::get('/', 'Admin\HomeController@index')->name('home');
       Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
       Route::post('/login', 'Auth\LoginController@login')->name('login');
       Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
       Route::get('/categories', 'Admin\CategoriesController@index')->name('categories');

       Route::get('/configs', 'Admin\ConfigsController@index')->name('configs');
       Route::get('/buttons', 'Admin\ButtonsController@index')->name('buttons');

       //Currency Admin
       Route::resource('currencies', 'Admin\CurrenciesController');
       Route::get('/currencies/{currency}/remove', 'Admin\CurrenciesController@remove')->name('currencies.remove');
       Route::resource('categories', 'Admin\CategoriesController');
       Route::get('/categories/{category}/remove', 'Admin\CategoriesController@remove')->name('categories.remove');
       Route::get('/categories/{category}/toggleShow', 'Admin\CategoriesController@toggleShow')->name('categories.toggleShow');
       Route::resource('configs', 'Admin\ConfigsController')->except(['destroy', 'create', 'store']);
       Route::resource('buttons', 'Admin\ButtonsController');
       Route::get('/buttons/{button}/remove', 'Admin\ButtonsController@remove')->name('buttons.remove');
    });
});

app/Models/Config.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Config extends Model {

    public $timestamps = false;

    public function get($name) {
        return $this->where('key', $name)->first()->value;
    }

}

app/Http/Controllers/Admin/ConfigsController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Services\ConfigService;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ConfigsController extends Controller {

    use AuthenticatesUsers;
    private $service;

    public function __construct(ConfigService $service) {
        $this->middleware('auth');
        $this->service = $service;
    }

    public function index(Request $request) {
        $configs = $this->service->getList();
        return view('config.list', ['configs'=>$configs]);
    }

    public function edit(Request $request, $id) {
        $config = $this->service->getSingleById($id);
        return view('config.editForm', ['config'=>$config]);
    }

    public function update(Request $request, $id) {
        $this->service->updateSingle($id, $request->toArray());
        return redirect(route('configs.index'));
    }
}

resources/views/config/addForm.blade.php
@extends('config.layout')

@section('page')
    <form method="post" action="{{ route('configs.store') }}">
        @csrf
        <div class="form-group">
            @foreach($configs as $config)
            <label for="config">{{ $config->key }}</label>
            <input type="text" class="form-control" id="categoryName" name="categoryName" placeholder="Enter config value" />
            @endforeach
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/config/deleteForm.blade.php
@extends('category.layout')

@section('page')
    <form method="post" action="{{ route('categories.destroy', ['category'=>$category->id]) }}">
        {!! method_field('DELETE') !!}
        @csrf
        <div class="form-group">
            <label for="categoryDelete">To Delete the {{ $category->name }} Category, type DELETE (all caps) and press Submit</label>
            <input type="text" class="form-control" id="categoryDelete" name="categoryDelete" />
        </div>
        <button type="submit" class="btn btn-danger">Submit</button>
    </form>
@endsection

resources/views/config/editForm.blade.php
@extends('config.layout')

@section('page')
    <form method="post" action="{{ route('configs.update', ['config'=>$config->id]) }}">
        @csrf
        {!! method_field('PUT') !!}
        <div class="form-group">
            <label for="{{ $config->key }}">{{ $config->key }}</label>
            <input type="text" class="form-control" id="{{ $config->key }}" name="{{ $config->key }}" placeholder="Enter {{ $config->key }}" value="{{ $config->value }}" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/config/layout.blade.php
@extends('layouts.admin_page')

@section('section')
    Config
@endsection

resources/views/config/list.blade.php
@extends('config.layout')

@section('page')
    <div class="text-right">
{{--        <x-add-action path="configs" name="Config" />--}}
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Key</th>
                <th scope="col">Value</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($configs as $config)
            <tr>
                <td>{{ $config->id }}</td>
                <td>{{ $config->key }}</td>
                <td>{{ $config->value }}</td>
                <td><a class="btn btn-success" href="{{ route('configs.edit', ['config'=>$config->id]) }}">Edit</a></td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection